### ISSUE TITLE
Setup Clarification

### ISSUE THREAD

**Issue by snppls** [Prince527GitHub/SwingSonic#2]
Hello, thanks for making this. It isn't clear to me from reading the project page but does this app provide a way of synchronising playlists, likes, and playlist history between Jellyfin and Swing Music?

If so, could you please give me a little help to get my instance running? Am I correct in thinking for Jellyfin the following should be filled out like this...

      - SERVER_PORT Is this supposed to be the port of Jellyfin?
      - SERVER_URL Is this the IP address and port of Jellyfin? Is an internal address ok?
      - SERVER_USERS_0_USERNAME Is this the Jellyfin username?

Every time I try, Docker throws this error:

swingsonic | node:internal/modules/cjs/loader:1146
swingsonic |   throw err;
swingsonic |   ^
swingsonic | 
swingsonic | Error: Cannot find module './config.json'
swingsonic | Require stack:
swingsonic | - /app/index.js
swingsonic |     at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
swingsonic |     at Module._load (node:internal/modules/cjs/loader:984:27)
swingsonic |     at Module.require (node:internal/modules/cjs/loader:1231:19)
swingsonic |     at require (node:internal/modules/helpers:179:18)
swingsonic |     at Object.<anonymous> (/app/index.js:4:53)
swingsonic |     at Module._compile (node:internal/modules/cjs/loader:1369:14)
swingsonic |     at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
swingsonic |     at Module.load (node:internal/modules/cjs/loader:1206:32)
swingsonic |     at Module._load (node:internal/modules/cjs/loader:1022:12)
swingsonic |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12) {
swingsonic |   code: 'MODULE_NOT_FOUND',
swingsonic |   requireStack: [ '/app/index.js' ]
swingsonic | }
swingsonic | 
swingsonic | Node.js v20.12.0
swingsonic exited with code 1

**Comment by Prince527GitHub** [comment]
Thank you for making an issue and sorry for the late reply,

To be honest, I'm not the best at making projects other people use so sorry if its a bit shit, but il try my best to answer your questions.

> app provide a way of synchronising playlists, likes, and playlist history between Jellyfin and Swing Music

No, the app only allow users to use clients from other music servers with Swing Music, it cant sync/move anything. This project is just for allowing people to use Finamp, Subtracks, Ultrasonic or any other app/client compatible with Jellyfin, Subsonic and Euterpe with Swing Music. *(sorry if my explanation sucked)*

> Every time I try, Docker throws this error

This is just a bug, thanks for pointing it out. To be honest, I never really tried the docker image but I suspected it would work the same but I guess thats not the case. So, thank you 😊!

**Comment by Simonh2o** [comment]
Thank you for creating this.

Do you mind helping/clarifying the setup for me?
I have jellyfin and swing running on the same server and would like to try finamp with my swing music server. Everytime i start the image with docker-compose I get:
swingsonic | > Subsonic ✘
swingsonic | > Jellyfin ✘
swingsonic | > Euterpe ✘
swingsonic | 404 GET     20     139 /

Any idea on how the docker-compose.yml should be?
I have tried changing it but I find it very confusing and i'm not sure what is needed for it to work as I described above.
What's the difference between the server port and server_url? It should be enough by only enabling jellyfin and setting jellyfin user/pass?
    environment:
      - SERVER_PORT=3000 # The port to listen on
      - SERVER_URL=http://192.168.100.18:80 # The public URL of this API
      - SERVER_API_SUBSONIC=false # Enable of disable Subsonic API implementation
      - SERVER_API_JELLYFIN=true # Enable of disable Jellyfin API implementation
      - SERVER_API_EUTERPE=false # Enable of disable Enterpe API implementation
      - SERVER_USERS_0_USERNAME=***** # First user's username
      - SERVER_USERS_0_PASSWORD=********* # First user's password
      - SERVER_PROXY=true # Whether to proxy the content
      - MUSIC_URL=http://192.168.100.18:3000 # The URL of your Swing Music server
      
0 0.0.0.0:3000          LISTEN      1472491/docker-prox

**Comment by Prince527GitHub** [comment]
Alright, il try me best to explain it :)

SERVER_PORT is used to change the port of the app running in the container. Which means if I take this section (first codeblock) of the docker compose, I can see that outside the container is set to 3000 and inside is 3000 too but lets say I wanted a different port, idk 4000, what should I change? The outside port (second codeblock), the only reason the app has an option to change the port is for people that dont use docker.
```yml
    ports:
      - 3000:3000
```
```yml
    ports:
      - 4000:3000
```

SERVER_URL is the url that the app is running on so if my SwingSonic is running on port 4000 (like in the second codeblock) then my SERVER_URL would be http://IP:4000. The problem there is that I would not be able to access my music on the go so thats where SERVER_PROXY and SERVER_URL would come in. In my case I use https://sonic.serversmp.xyz as my SERVER_URL because I gave my server a domain. SERVER_PROXY allows me to take the music from SwingMusic and well proxy it through my SwingSonic.

I'm gonna make some images to help explain this.

1. SERVER_URL set to local url and the api is accessed from outside the network
2. SERVER_URL set to public url and the api is accessed from outside the network
3. SERVER_URL set to local url and the api is accessed from inside the network
4. What SERVER_PROXY does (I know you did not ask about it but I wanted to mention it)

![local url but public](https://api.serversmp.xyz/upload/66a13f367036ecb33d718459.webp)
![local with public url but public](https://api.serversmp.xyz/upload/66a13f407036ecb33d718463.webp)
![completely local](https://api.serversmp.xyz/upload/66a13d8e7036ecb33d718439.webp)
![proxy](https://api.serversmp.xyz/upload/66a13a477036ecb33d718425.webp)

I will say it is a bit odd that that none of the implementations returned check boxes.

This is what I get
```
> Subsonic ✘
> Jellyfin ✔
> Euterpe ✘
```

```yml
# THIS IS OUTDATED USE THE ONE IN THE README
version: '3'

services:
  app:
    image: ghcr.io/prince527github/swingsonic:main
    container_name: swingsonic
    ports:
      - 3000:3000
    environment:
      - SERVER_PORT=3000
      - SERVER_URL=http://192.168.2.17:3000 # this is my internal ip address
      - SERVER_API_SUBSONIC=false 
      - SERVER_API_JELLYFIN=true
      - SERVER_API_EUTERPE=false
      - SERVER_USERS_0_USERNAME=prinky
      - SERVER_USERS_0_PASSWORD=verysecurepassword
      - SERVER_PROXY=true
      - MUSIC_URL=http://192.168.2.17:1007 # this is my internal ip address
```

I hope this helps, as you can tell I'm not the best at explaining things but I try, if you have any more questions, feel free to ask and il try my best to respond.

**Comment by Simonh2o** [comment]
Great explanation, thank you!
Finally managed to get a checkmark next to jellyfin, I believe it somehow didn't start with the docker-compose.yml previously.
I tried logging in on finamp with the new server url (swingsonic server on port 3000) and get a black screen with the exclamation mark icon in the middle. It seems stuck somehow

Tried this: 3. SERVER_URL set to local url and the api is accessed from inside the network

Error:
ClientException with SocketException:
Connection refused (OS Error: errno = 111),
address = 192.168.100.18, port 47558, url=http://192.168.100.18:3000/Users/AuthenticateByName,
http://192.168.100.18:3000/Users/Views

Edit:
Log from swingsonic server:
swingsonic | > Jellyfin ✔
swingsonic | node:internal/deps/undici/undici:12502
swingsonic |       Error.captureStackTrace(err, this);
swingsonic |             ^
swingsonic |
swingsonic | TypeError: Failed to parse URL from [object Object]/folder
swingsonic |     at node:internal/deps/undici/undici:12502:13
swingsonic |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
swingsonic |     at async /app/router/jellyfin/users.js:7:28 {
swingsonic |   [cause]: TypeError: Invalid URL
swingsonic |       at new URL (node:internal/url:797:36)
swingsonic |       at new Request (node:internal/deps/undici/undici:4853:25)
swingsonic |       at fetch (node:internal/deps/undici/undici:9662:25)
swingsonic |       at fetch (node:internal/deps/undici/undici:12500:10)
swingsonic |       at value (node:internal/bootstrap/web/exposed-window-or-worker:72:12)
swingsonic |       at /app/router/jellyfin/users.js:7:34
swingsonic |       at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
swingsonic |       at next (/app/node_modules/express/lib/router/route.js:144:13)
swingsonic |       at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
swingsonic |       at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5) {
swingsonic |     code: 'ERR_INVALID_URL',
swingsonic |     input: '[object Object]/folder'
swingsonic |   }
swingsonic | }
swingsonic | Node.js v20.15.1

Any idea?

**Comment by Prince527GitHub** [comment]
Its a bug, I'm working on a debugging it right now, sorry for the delay in responding

**Comment by Prince527GitHub** [comment]
ah I see change `MUSIC_URL` to `MUSIC` in the env

**Comment by Simonh2o** [comment]
Thanks! Will test when able

**Comment by Simonh2o** [comment]
Playing and downloading songs/playlists seem to be working. I am not able to search for albums/artists/playlists/tracks. Artists and playlists are missing thumbnails. Is it possible to see favorited songs from swing? Currently it says no items found. Search is also not working at all, is this the expected behavior? Thanks.

**Comment by Prince527GitHub** [comment]
Sadly thats the limitation of the project in its current state.

- Artists thumbnails: Sadly I could not find a good way to load them quickly the thing I tested added like 30 seconds per thumbnail (too slow, I try to find a balance between speed and usability)
  - Unless im getting it confused with another thing I tried, il look into it again

- Playlists thumbnails: I just never implemented it, looking at it right now it should be not too bad, so il add it to my todo list
- Search: Another thing I never implemented, converting SwingMusic's api to Jellyfin is not easy
- Favorited songs: You can see your favorites when you click on the album and modify them (add or remove) but there is no favorited menu where you can see all of them (not implemented)

So pretty much most of the problems are just because I have not coded it in yet, sorry.

**Comment by Simonh2o** [comment]
Alright it's working as intended then! I was sadly looking for a way to at least see my favorited songlist.

**Comment by mia-riezebos** [comment]
the example posted above is a little outdated compared to the README. This leads to a little confusion as to which one is the SoT...

In any case I'm getting a bunch of 404s.

```
swingsonic       |    ▄▄▄▄▄    ▄ ▄   ▄█    ▄     ▄▀    ▄▄▄▄▄   ████▄    ▄   ▄█ ▄█▄      ▄
swingsonic       |   █     ▀▄ █   █  ██     █  ▄▀     █     ▀▄ █   █     █  ██ █▀ ▀▄   █
swingsonic       | ▄  ▀▀▀▀▄  █ ▄   █ ██ ██   █ █ ▀▄ ▄  ▀▀▀▀▄   █   █ ██   █ ██ █   ▀  █
swingsonic       |  ▀▄▄▄▄▀   █  █  █ ▐█ █ █  █ █   █ ▀▄▄▄▄▀    ▀████ █ █  █ ▐█ █▄  ▄▀ █
swingsonic       |            █ █ █   ▐ █  █ █  ███                  █  █ █  ▐ ▀███▀
swingsonic       |             ▀ ▀      █   ██                       █   ██           ▀
swingsonic       |
swingsonic       | > Subsonic ✔
swingsonic       | > Jellyfin ✔
swingsonic       | > Euterpe ✘
swingsonic       | 404 GET     12     139 /
swingsonic       | 404 GET      2     139 /
```

My docker-compose.yaml (truncated)
```yaml
  swingsonic:
    image: ghcr.io/prince527github/swingsonic:main
    container_name: swingsonic
    networks:
      - default
      - traefik
    # ports:
    #   - 3000:3000
    volumes: # Use a config.json file or env (see below)
      - ./swingsonic/config.json:/app/config.json
    environment:
      - "SERVER_PORT=3000" # The port to listen on
      - "SERVER_URL=https://swingsonic.media.domain.tld" # The public URL of this API
      - "SERVER_API_SUBSONIC_ENABLE=false" # Enable of disable Subsonic API implementation
      - "SERVER_API_SUBSONIC_OPTIONS_ZW=false" # Enable of Zero Width Character Hack
      - "SERVER_API_JELLYFIN_ENABLE=true" # Enable of disable Jellyfin API implementation
      - "SERVER_API_JELLYFIN_USER_USERNAME=username" # Jellyfin implementation requires a Swing Music user's username
      - "SERVER_API_JELLYFIN_USER_PASSWORD=password" # Jellyfin implementation requires a Swing Music user's password
      - "SERVER_API_EUTERPE=false" # Enable of disable Enterpe API implementation
      - "SERVER_PROXY=true"
      - "MUSIC=https://swing.media.domain.tld" # The URL of your Swing Music server
    labels:
      tld.domain.internal.network.machine.media.swingsonic: ""

      service: "media.machine.network.internal.domain.tld"

      traefik.enable: "true"
      
      traefik.http.routers.swingsonic.entrypoints: "https"
      traefik.http.services.swingsonic.loadbalancer.server.port: "3000"
      traefik.http.routers.swingsonic.rule: 'Host(`swingsonic.media.machine.network.internal.domain.tld`) || Host(`swingsonic.media.domain.tld`)'
      traefik.http.routers.swingsonic.tls: "true"
      traefik.http.routers.swingsonic.tls.certresolver: "cloudflare"
```

What am I doing wrong?

The logs aren't hugely helpful.

**Comment by Prince527GitHub** [comment]
> In any case I'm getting a bunch of 404s.
>
>...
>
> What am I doing wrong?

The 404s are on purpose because Swingsonic has no UI it just has the endpoints for each APIs compatibility layer (ex: `/rest/getAlbumList` for Subsonic). The client you use should use the endpoints it needs but not all clients are compatible as I dont have 100% coverage of the APIs.

Also, I see you've enable Jellyfin which has the least compatibility of the 3, this is manly because of how some clients communicate with Jellyfin, some will use the API (ex: Finamp) while others scrape the UI. The ones that scrape the UI wont work.

Hope this helps, if you have anymore questions just send them and il do my best to reply.

**Comment by mia-riezebos** [comment]
Unfortunate, as the fintunes app uses a login to fetch authentication so i wont be able to use it with swingsonic :(

**Comment by Prince527GitHub** [comment]
> Unfortunate, as the fintunes app uses a login to fetch authentication so i wont be able to use it with swingsonic :(

Good news, I got it working.

So Ive been thinking about this all day and it hit me, the Jellyfin webui is a separate project that can be hosted on its own so Swingsonic + Jellyfin Web = Working. With this idea I forked the [webui](https://github.com/ForkPrince/jellyfin-web) to remove the version check, build a [docker image](https://github.com/orgs/ForkPrince/packages/container/package/jellyfin-web) and deploy it to [github pages](https://forkprince.github.io/jellyfin-web/).

<details>
<summary>Docker Compose</summary>

This is an docker compose you can use this or the [github pages](https://forkprince.github.io/jellyfin-web/).

```yml
version: '3'

services:
  app:
    image: ghcr.io/forkprince/jellyfin-web:master
    container_name: jellyfin-web
    ports:
      - 3000:80
```

</details>

Then I ran it, connected to it on Fintunes, inputed my Swingsonic server, logged in, when to the "Favorites" tab then clicked "Albums" and boom it worked.

[[video showing the process with the ios version running on my mac]](https://api.serversmp.xyz/upload/6890935c7204612b83a5cabf.mov)
*(the progress bar seems broken on the ios version running this way but works fine on android)*
Also you should be able to use the [github pages deployment](https://forkprince.github.io/jellyfin-web/) in any environment because all the request are done in the browser/locally.
